### ISSUE TITLE
iOS: succes/error callbacks

### ISSUE THREAD

**Issue by rchovan** [litehelpers/Cordova-sqlite-legacy-build-support#11]
Hi, 
I have my project in cordova for Android. Now I want to build it for iOS, but DB on iOS won't open. I have discovered, that success or error callbacks are not fired on iOS. Same code on Android is running without problem. 

```
var db = window.sqlitePlugin.openDatabase({name: 'NoCache/test.db', iosDatabaseLocation: 'Documents'}, 
function() {
   alert("opened");
}, 
function(error) {
   alert ("error: " + error);
});
```

**Comment by brodybits** [comment]
I already documented that it is not supported to open a database in a subdirectory.

The newer `location: 'default'` setting will store the database in a location with no cloud backup. This is also documented.

**Comment by rchovan** [comment]
Hi, sorry, missed it. 
According to docs:
> default: Library/LocalDatabase subdirectory - NOT visible to iTunes and NOT backed up by iCloud

I need:

1.  that my database is visible to iTunes (to copy from/to Windows PC), and not backed up to cloud. 
1.  import database from import subfolder and export to export subfolder 

is there any workaround for that ? 

Thank You.

**Comment by brodybits** [comment]
> that my database is visible to iTunes (to copy from/to Windows PC), and not backed up to cloud

According to <https://github.com/apache/cordova-plugin-file#ios-file-system-layout> this would be the `Documents/NoCloud` directory.

I am thinking the best way to support this is to adapt the iOS version to use an arbitrary database location. I am thinking to do this at some point in the future not have not decided when. For priority fixes and features please contact <sales@litehelpers.net> for an estimate.

> import database from import subfolder and export to export subfolder

I do not really understand what you want to achieve with this. I think this should be possible with support of cordova-plugin-file. For priority support please contact <sales@litehelpers.net> for rates.
