### ISSUE TITLE
Can we create windows 10 cordova app on windows 8.1

### ISSUE THREAD

**Issue by bajajsu16** [litehelpers/Cordova-sqlite-legacy-build-support#12]
Please suggest, if yes then can we use cordova sql lite plugin for data storage.
Please share some document link if possible.
Also please suggest if we could test the windows cordova app without having any developer account.

**Comment by brodybits** [comment]
Answers given in https://github.com/litehelpers/Cordova-sqlite-help/issues/12

**Comment by bajajsu16** [comment]
Hi Thanks,

For your reply.
But i need to use cordova sqlite storage plugin with this plugin, which does not support windows universal app platform.
Please suggest.

**Comment by bajajsu16** [comment]
Please reply can we download windows 10 emulators on windows 8.1 
if yes please share the link if possible.
