### ISSUE TITLE
iOS: Error during Phonegap build

### ISSUE THREAD

**Issue by ekntrtmz** [litehelpers/Cordova-sqlite-legacy-build-support#13]
During Phonegap build I get this error:

>  Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: cordova-sqlite-legacy-build-support 

**From log file:**

** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Users/phonegap/Library/Developer/Xcode/DerivedData/ProjectBody-fxkcblxtmwdhqhaiqtcdjorsdygv/Build/Intermediates/ArchiveIntermediates/ProjectBody/IntermediateBuildFilesPath/ProjectBody.build/Release-iphoneos/ProjectBody.build/Objects-normal/arm64/SQLitePlugin.o ProjectBody/Plugins/cordova-sqlite-legacy-build-support/SQLitePlugin.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/private/tmp/gimlet/2680829/project/cordova/build-release.xcconfig,-workspace,ProjectBody.xcworkspace,-scheme,ProjectBody,-configuration,Release,-destination,generic/platform=iOS,-archivePath,ProjectBody.xcarchive,archive,CONFIGURATION_BUILD_DIR=/private/tmp/gimlet/2680829/project/build/device,SHARED_PRECOMPS_DIR=/private/tmp/gimlet/2680829/project/build/sharedpch

**Comment by brodybits** [comment]
More information is needed if this is still an issue.

**Comment by ekntrtmz** [comment]
Sorry. Has been a while. Cannot reconstruct the issue...

**Comment by brodybits** [comment]
Thanks for the response, closing for now. Please report if you encounter this kind of issue again.
