### ISSUE TITLE
New version after upate does not use data from older version?

### ISSUE THREAD

**Issue by uj** [litehelpers/Cordova-sqlite-legacy-build-support#14]
I built an Android application back in February 2017 using the current plugin version at that time, and it worked fine.  Then, I rebuilt the application with the newest version of this plugin recently.

When I do an Android upgrade from the old built app to the new built app, the old data is no longer there so it starts with a blank database.

New data seems to work properly, but I need it to use the old/existing data during the update.

Has something changed that would cause the data from the February version to not show up in the current version after an update?

**Comment by brodybits** [comment]
This should not happen on Android. More information is needed to reproduce.

**Comment by brody2consult** [comment]
Closing for now. Please report if you would like to share any more information.
