### ISSUE TITLE
No longer building on PhoneGap Build

### ISSUE THREAD

**Issue by DamiJegede** [litehelpers/Cordova-sqlite-legacy-build-support#15]
We switched to this plugin for PhoneGap build support, since that's how we roll. But since the last update, our build are now failing with this:

Error - Plugin error (you probably need to remove plugin files from your app): //github.com/litehelpers/Cordova-sqlite-legacy-build-support": Fetching plugin "https://github.com/litehelpers/Cordova-sqlite-legacy-build-support" via git clone Cloning full repository Failed to fetch plugin https://github.com/litehelpers/Cordova-sqlite-legacy-build-support via git. Either there is a connection problems, or plugin spec is incorrect: Error: git: Command failed with exit code 1 Error output: error: pathspec 'master' did not match any file(s) known to git.

**Comment by brody2consult** [comment]
Hey you have to use <https://github.com/brodybits/cordova-sqlite-legacy-build-support> to get PhoneGap Build support. This is already documented, evidently not clear enough. My apologies for the confusion.

Also the error message indicates to me that PhoneGap Build does not follow redirect for some reason.

**Comment by DamiJegede** [comment]
Fantastic @brodybits! We're good and back on. Thanks for the gift of this plugin.

**Comment by brody2consult** [comment]
On Wed, Dec 27, 2017 at 12:17 PM, Damilola Rafael Jegede <
notifications@github.com> wrote:

> Fantastic @brodybits <https://github.com/brodybits>! We're good and back
> on. Thanks for the gift of this plugin.
>
>
Thanks for the encouraging feedback. Will fix the documentation (someday).
