### ISSUE TITLE
SQLite 3.26.0 update needed - SECURITY ISSUE

### ISSUE THREAD

**Issue by brody2consult** [litehelpers/Cordova-sqlite-legacy-build-support#20]
due to known vulnerability in SQLite pre-2.25.0

**Comment by snehasis** [comment]
What is the plan to move to the SQLite 3.26.0 ? 
I see cordova-sqlite-ext-deps is already adopted the 3.26.0 SQLite

**Comment by brody2consult** [comment]
Now done.

Please keep in mind that this plugin version has very limited support, as documented.

**Comment by snehasis** [comment]
@brodybits Thanks for the quick solution.
