### ISSUE TITLE
W10 - sqlitePlugin undefined

### ISSUE THREAD

**Issue by mareksip** [litehelpers/Cordova-sqlite-legacy-build-support#3]
After changing the app Package name and Start page accordingly in package.windows10.appxmanifest. The `sqlitePlugin` is undefined. When using the original name from cordova CLI build, everything works.

Not sure if related to this plugin or VS2015.

Thanks for investigating.

**Comment by brodybits** [comment]
Thanks for reporting. This is definitely not supported and I will document this when I get a chance.

**Comment by mareksip** [comment]
The problem is that Windows Store has its own Package Identification system and the package ID is reserved on the Store page, unlikely from Google Play where it is set in the package config. So it is not possible to have same ID for Android and Windows 10 app.

[WINSTORE_ID].[PROFILE_NAME].[APP_NAME] seems very similar to Google Play, but is being by Corodova build marked as invalid Widged ID.

Do you have an idea where is the issue?

**Comment by mareksip** [comment]
@brodybits 

The problem is that Windows Store has its own Package Identification system and the package ID is reserved on the Store page, unlikely from Google Play where it is set in the package config. So it is not possible to have same ID for Android and Windows 10 app.

[WINSTORE_ID].[PROFILE_NAME].[APP_NAME] seems very similar to Google Play, but is being by Corodova build marked as invalid Widged ID.

Do you have an idea where is the issue?

**Comment by brodybits** [comment]
I cannot promise when I would have a chance to investigate this one. I think you found a solution so I will document it when I get a chance.

**Comment by michaelwalgraeve** [comment]
Any progress on this? I have the same issue. When I build in debug/release mode my app works fine. But after I have linked the app to the Windows Store (i.e. the package name has changed) I am not able to build my app anymore. I get an error saying (see image)

![image](https://cloud.githubusercontent.com/assets/8089418/16837332/05e28066-49c3-11e6-983c-63f1f761e078.png)

**Comment by brodybits** [comment]
@mareksip gave the following workaround:

> So far, it seems that WindowsStoreIdentityName preference within widget (Config.xml) fixes this.

Also this looks like an issue with the Cordova framework and is *not* specific to this plugin. Or am I mistaken somehow?

**Comment by michaelwalgraeve** [comment]
It isn't really clear what mareskip meant by this so I did the following:

- Commented out this line in config.xml of the Cordova app -> No different result
- Simplified name in config.xml of the Cordova app -> No different result
- Added this line to Config.xml in "platforms/windows/CordovaApp.Windows10" -> No different result

Am I missing something? 
And I don't know if this is a Cordova framework issues because I can publish my app if I delete the SQLite plugin...

**Comment by brodybits** [comment]
According to <https://cordova.apache.org/docs/en/latest/config_ref/> you can set the `WindowsStoreIdentityName` preference in `config.xml`.

If you change the package name manually then Cordova cannot find the necessary Windows build projects specified in `plugin.xml`. Most of the other plugins do not need to include such Windows build projects.

This is now marked as a documentation bug, to be resolved in other versions such as Cordova-sqlite-storage, cordova-sqlite-ext, and Cordova-sqlcipher-adapter as well.

**Comment by mareksip** [comment]
@michaelwalgraeve Could not copy the file.. SQLite3.winmd tells you that you haven't added [this project](https://github.com/litehelpers/Cordova-sqlite-legacy-build-support/tree/legacy-build-master/src/windows/SQLite3-Win-RT/SQLite3) to your CordovaApp solution references.

**Comment by brodybits** [comment]
> @michaelwalgraeve @brodybits This is entirely different issue that the original post.
> 
> Could not copy the file.. SQLite3.winmd tells that you haven't added this project to your CordovaApp solution but only included reference to it in CordovaApp.Windows10.

@mareksip that indicates a build problem. If you continue to see this problem please be sure to capture **all** of the output from the Output tab and put it in a new issue.

**Comment by michaelwalgraeve** [comment]
Closing this issue because it is clearly a Cordova issue. When building my app for different platforms in the same solution I get mixed up references.
